#!/usr/bin/env node
/**
 * Runs the Prisma CLI against the right schema for DATABASE_URL:
 *  - file:…                     → prisma/schema.prisma (SQLite, local dev and tests)
 *  - postgres:// | postgresql:// → prisma/postgres/schema.prisma (Supabase), generated
 *    from the SQLite schema with the provider swapped and DIRECT_URL for migrations
 *
 *   node scripts/prisma.mjs generate
 *   node scripts/prisma.mjs db push --skip-generate
 *
 * One schema to edit; the Postgres copy is derived and gitignored.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const base = path.join(root, "prisma", "schema.prisma");
const url = process.env.DATABASE_URL ?? "";
let schema = base;

if (/^postgres(ql)?:\/\//.test(url)) {
  const src = fs.readFileSync(base, "utf8");
  const pg = src.replace(
    /datasource db \{[^}]*\}/,
    `datasource db {\n  provider  = "postgresql"\n  url       = env("DATABASE_URL")\n  directUrl = env("DIRECT_URL")\n}`,
  );
  if (pg === src) throw new Error("Could not find the datasource block in prisma/schema.prisma");
  schema = path.join(root, "prisma", "postgres", "schema.prisma");
  fs.mkdirSync(path.dirname(schema), { recursive: true });
  fs.writeFileSync(schema, `// GENERATED by scripts/prisma.mjs from ../schema.prisma. Do not edit.\n${pg}`);
  if (!process.env.DIRECT_URL) process.env.DIRECT_URL = url;
}

const r = spawnSync("npx", ["prisma", ...process.argv.slice(2), "--schema", schema], { stdio: "inherit", env: process.env });
process.exit(r.status ?? 1);
